apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: vovakoto97@mail.ru
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
