global:
  # Обязательные базовые настройки
  application:
    create: true
    name: gitlab
  
  common:
    labels: {}
  
  service:
    labels: {}  # Добавляем пустые labels для сервиса
  
  image:
    tagSuffix: ""
  
  serviceAccount:
    enabled: true
    create: true
  
  initialRootPassword:
    secret: gitlab-initial-root-password
    key: password
  
  hosts:
    domain: k8s.djabjo.ru
    externalIP: ""
    https: true
    
    gitlab:
      name: gitlab.k8s.djabjo.ru
      https: true
    
    registry:
      name: registry.k8s.djabjo.ru
      https: true
    
    ingress:
      configureCertmanager: true
      class: nginx
      tls:
        enabled: true
        secretName: gitlab-tls

  ingress:
    enabled: true
    configureCertmanager: true
    tls:
      enabled: true
      secretName: gitlab-tls
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"

# Остальная конфигурация остается без изменений...
# [Вставьте сюда остальные секции из предыдущего конфига]

gitlab:
  webservice:
    enabled: true
    replicaCount: 1
    ingress:
      enabled: true
      path: /
      pathType: Prefix
      tls:
        enabled: true
        secretName: gitlab-tls
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 3Gi
        cpu: 1

# Отключаем cert-manager (используем предустановленный)
certmanager:
  install: false

# Отключаем встроенный ingress-nginx
nginx-ingress:
  enabled: false


  # Sidekiq
  sidekiq:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 300m
      limits:
        memory: 2Gi
        cpu: 500m

  # Toolbox
  toolbox:
    enabled: true
    persistence:
      enabled: false

  # Gitaly
  gitaly:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi

  # GitLab Shell
  gitlab-shell:
    enabled: true
    replicaCount: 1

  # Registry
  registry:
    enabled: true
    ingress:
      enabled: true
      host: registry.k8s.djabjo.ru
    resources:
      requests:
        memory: 1Gi
        cpu: 200m
      limits:
        memory: 2Gi
        cpu: 500m
    storage:
      secret: registry-storage
      extraKey: config
      backend: filesystem
    persistence:
      enabled: true
      size: 50Gi

# База данных PostgreSQL
postgresql:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 500m

# Redis
redis:
  enabled: true
  master:
    persistence:
      enabled: true
      size: 5Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 500m

# Отключаем ненужные компоненты
prometheus:
  install: false

alertmanager:
  enabled: false

grafana:
  enabled: false

gitlab-runner:
  enabled: false

minio:
  enabled: false

mattermost:
  enabled: false

pages:
  enabled: false