global:
  hosts:
    domain: k8s.djabjo.ru
    externalIP: 10.10.10.10
  ingress:
    configureCertmanager: true
    tls:
      enabled: true
      secretName: gitlab-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    class: nginx

certmanager:
  install: false

certmanager-issuer:
  email: vovakotov97@mail.ru

nginx-ingress:
  enabled: false