# values.yaml для минимальной установки GitLab

global:
  # Отключаем ненужные компоненты
  ingress:
    configureCertmanager: false
    enabled: false
  minio:
    enabled: false
  certmanager:
    install: false
  # Используем встроенный PostgreSQL и Redis
  psql:
    host: ""
    password:
      secret: gitlab-postgres
      key: password
  redis:
    password:
      enabled: false

# Отключаем автоматическое создание ingress-ресурсов
nginx-ingress:
  enabled: false

# Отключаем cert-manager
certmanager:
  install: false

# Конфигурация GitLab
gitlab:
  webservice:
    replicas: 1  # Одна реплика веб-интерфейса
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

  sidekiq:
    replicas: 1
    resources:
      requests:
        cpu: 300m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

  gitlab-shell:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

# Используем встроенное хранилище вместо MinIO
gitlab-runner:
  install: false

registry:
  enabled: false

# Отключаем мониторинг и аналитику
prometheus:
  install: false
grafana:
  install: false

# Конфигурация PostgreSQL (встроенный)
postgresql:
  enabled: true
  image:
    tag: "13.6"
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

# Конфигурация Redis (встроенный)
redis:
  enabled: true
  master:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi