server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/tls-acme: 'true'
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/letsencrypt-prodbackend-protocol: "HTTPS" 
    
    hostname: argocd.djabjo.ru
    tls:
    - hosts:
      - argocd.djabjo.ru
  host: argocd.djabjo.ru