
host: argocd.test.djabjo
# destinationServer: https://kubernetes.default.svc
server:
  ingress:
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    ingressClassName: nginx
    hostname: argocd.test.djabjo
    tls:
    - hosts:
      - argocd.test.djabjo
