apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
spec:
  destinations:
    - name: '*'
      namespace: '*'
      server: {{ .Values.destinationServer }}
  sourceRepos:
    - {{ .Values.repoURL }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: monitoring
      server: {{ .Values.destinationServer }}
    - namespace: kube-system
      server: {{ .Values.destinationServer }}
  sourceRepos:
    - https://gitlab.dsys.ai/charts/monitoring.git
